backend:
  name: 'git-gateway'
  branch: 'master'
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: 'article'
    label: 'Articles'
    folder: 'src/pages/articles'
    create: true
    delete: true
    slug: 'index'
    path: '{{title}}/index'
    extension: 'md'
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Data publikacji', name: 'date', widget: 'datetime' }
      - { label: 'Opis', name: 'description', widget: 'text' }
      - { label: 'Zawartość artykułu', name: 'body', widget: 'markdown' }
      - { label: 'Tagi', name: 'tags', widget: 'list' }
  - name: 'pages'
    label: 'Strony'
    files:
      - name: 'reading'
        label: 'Readings'
        file: 'static/readings/books.json'
        extension: 'json'
        format: 'json'
        media_folder: 'src/img'
        public_folder: '/books-covers'
        fields:
          - {
              label: 'Books',
              name: 'books',
              widget: 'list',
              fields:
                [
                  { label: 'Nazwa', name: 'name', widget: 'string' },
                  { label: 'Link', name: 'link', widget: 'string' },
                  { label: 'Zdjęcie', name: 'image', widget: 'image' },
                ],
            }
