backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'src/pages/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}/{{slug}}'
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Data publikacji', name: 'date', widget: 'datetime' }
      - { label: 'Opis', name: 'description', widget: 'text' }
      - { label: 'Post', name: 'body', widget: 'markdown' }
      - label: 'Grafiki',
        name: 'images', 
        widget: 'image', 
        media_library: 
          config: 
            multiple: true 
      - { label: 'Tagi', name: 'tags', widget: 'list' }
  - name: 'readings'
    label: 'Readings'
    folder: 'src/pages/readings'
    slug: 'index'
    fields:
      - label: 'Grafiki',
        name: 'images', 
        widget: 'image', 
        media_library: 
          config: 
            multiple: true 
      - { label: 'Content', name: 'body', widget: 'markdown' }
